\hypertarget{classcurlpp_1_1UnknowException}{\section{curlpp\-:\-:Unknow\-Exception Class Reference}
\label{classcurlpp_1_1UnknowException}\index{curlpp\-::\-Unknow\-Exception@{curlpp\-::\-Unknow\-Exception}}
}


This exception is thrown when an exception is thrown within a callback without the curlpp\-::raise\-Exception function.  




{\ttfamily \#include $<$Exception.\-hpp$>$}



Inheritance diagram for curlpp\-:\-:Unknow\-Exception\-:\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=208pt]{classcurlpp_1_1UnknowException__inherit__graph}
\end{center}
\end{figure}


Collaboration diagram for curlpp\-:\-:Unknow\-Exception\-:\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=208pt]{classcurlpp_1_1UnknowException__coll__graph}
\end{center}
\end{figure}
\subsection*{Additional Inherited Members}


\subsection{Detailed Description}
This exception is thrown when an exception is thrown within a callback without the curlpp\-::raise\-Exception function. 

The documentation for this class was generated from the following files\-:\begin{DoxyCompactItemize}
\item 
include/curlpp/Exception.\-hpp\item 
src/curlpp/Exception.\-cpp\end{DoxyCompactItemize}
